global:
  scrape_interval: 5s

remote_write:
  - url: http://mimir:9009/api/v1/push

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["nodeexporter:9100"]

  - job_name: "pm2"
    static_configs:
      - targets: ["pm2exporter:9200"]

  - job_name: "nestjs"
    static_configs:
      - targets: ["host.docker.internal:9464"]
